version: "3"

services:
  frontend:
    build: ./frontend
    container_name: "chaftech-frontend"
    ports:
      - 3000:3000
    env_file:
      - .env.frontend
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: "chaftech-backend"
    ports:
      - 8000:8000
    env_file:
      - .env.backend
    depends_on:
      - database

  database:
    image: postgres
    container_name: "chaftech-database"
    env_file:
      - .env.database
    ports:
      - 5432:5432
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database:
