name: deploy-craftech-nginx

on:
  push:
    branches: ["main"]
    paths: ["prueba-3/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: cd prueba-3 && docker build --tag fedapon/craftech-nginx .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push fedapon/craftech-nginx

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Swarm
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_ADDRESS }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_KEY }}
          script: |
            # docker service create -d --name craftech-nginx -p 80:80 fedapon/craftech-nginx
            docker service update -d --update-order start-first --image fedapon/craftech-nginx craftech-nginx
