name: deploy-craftech-nginx

on:
  push:
    branches: ["main"]
    paths: ["prueba-3/**"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: cd prueba-3 && docker build --tag fedapon/craftech-nginx .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push the Docker image
        run: docker push fedapon/craftech-nginx
